export const IPC_CHANNELS = {
  settingsGet: "settings:get",
  settingsSave: "settings:save",
  settingsResetShortcuts: "settings:reset-shortcuts",
  settingsChanged: "settings:changed",
  historyGet: "history:get",
  historyClear: "history:clear",
  historyDelete: "history:delete",
  historyUpdate: "history:update",
  historyTogglePin: "history:toggle-pin",
  historyCopy: "history:copy",
  historyPasteSlot: "history:paste-slot",
  historyChanged: "history:changed",
  appOpenSettings: "app:open-settings",
  appOpenHistory: "app:open-history",
  appShowView: "app:show-view",
  hotkeysGetStatus: "hotkeys:get-status",
  hotkeysChanged: "hotkeys:changed",
  slotPickerGetContext: "slot-picker:get-context",
  slotPickerSubmit: "slot-picker:submit",
  slotPickerCancel: "slot-picker:cancel"
} as const;
